kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ $.Values.product }}
  labels:
    app: {{ $.Values.product }}
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    app: {{ $.Values.product }}
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ $.Values.product }}
      annotations:
        collectord.io/logs-output: splunk::prod
        collectord.io/logs-index: {{ $.Values.splunkIndex }}
{{- include "timestamp.onlatest" (dict "Values" $.Values "imageVersion" $.Chart.AppVersion) | indent 8 }}
    spec:
      containers:
      - name: {{ $.Values.product }}
        image: docker.bin.sbb.ch/tms/api-validation:{{ $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        env:
        - name: TZ
          value: UTC
        - name: VERSION
          value: {{ $.Chart.AppVersion }}
        ports:
        - containerPort: 8060
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 250Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8060
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 20
          successThreshold: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30