kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $.Values.product }}
  annotations:
    haproxy.router.openshift.io/timeout: 10m
    router.openshift.io/cookie-same-site: Strict
spec:
  host: {{ $.Values.product }}.{{ $.Values.clusterurl }}
  path: /
  port:
    targetPort: 8060-tcp
  to:
    kind: Service
    name: {{ $.Values.product }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: '{{ $.Values.product }}-cluster-independent'
  annotations:
    clew.sbb.ch/cluster-independent-dns: 'true'
    haproxy.router.openshift.io/timeout: 10m
    router.openshift.io/cookie-same-site: Strict
spec:
  host: {{ $.Values.hostnamePrefix }}.sbb-cloud.net
  path: /
  port:
    targetPort: 8060-tcp
  to:
    kind: Service
    name: {{ $.Values.product }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

