kind: Service
apiVersion: v1
metadata:
  name: {{ $.Values.product }}
spec:
  ports:
  - name: 8060-tcp
    port: 8060
    protocol: TCP
    targetPort: 8060
  selector:
    app: {{ $.Values.product }}
  sessionAffinity: None
  type: ClusterIP